data:
  data_name: DrugOOD-3D
  log_dir: ../logging
  dataset_dir: ../dataset
  feature_type: only_x
  setting: No-Info
  metrics: auc


optimizer:
  batch_size: 256
  wp_lr: 1.0e-3
  wp_wd: 1.0e-5
  attn_lr: 1.0e-3
  attn_wd: 1.0e-5
  emb_lr: 1.0e-3
  emb_wd: 1.0e-5

lri_bern:
  dgcnn:
    final_r: 0.6
  egnn:
    final_r: 0.7
  pointtrans:
    final_r: 0.7

  kr: 3
  one_encoder: true
  epochs: 100
  info_loss_coef: 0.1
  attn_constraint: none
  temperature: 1.0
  decay_interval: 10
  decay_r: 0.1
  init_r: 0.9
  pred_loss_coef: 1.0
  dropout_p: 0.2
  norm_type: batch
  act_type: relu

erm:
  kr: 3
  epochs: 100
  one_encoder: true

mixup:
  epochs: 100
  kr: 3
  one_encoder: true
  alpha: 0.1
  num_classes: 2
  prob: 0.5

groupdro:
  epochs: 100
  kr: 3
  one_encoder: true
  coeff: 0.1

dir:
  kr: 3
  epochs: 100
  one_encoder: False
  alpha: 1.0e-4
  causal_ratio: 0.5
  dropout_p: 0.2
  norm_type: batch
  act_type: relu

VREx:
  epochs: 100
  kr: 3
  one_encoder: true
  coeff: 0.001

coral:
  epochs: 100
  iters_per_epoch: 150
  kr: 3
  one_encoder: true
  coeff: 0.1

DANN:
  epochs: 100
  iters_per_epoch: 150
  kr: 3
  one_encoder: true
  coeff: 0.001
  max_iters: 1000
  dropout_p: 0.2
  norm_type: batch
  act_type: relu

shift:
  scaffold:
    shift_name: scaffold
    restrict_TL_train: 500
    target: lbap_core_ic50_scaffold
